# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'


baseURL = "http://automationismagic.blog/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Automation is Magic"
copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4

[params]
subtitle = "Lerning new things, while making (and breaking) stuff"
enableGitalk = true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Automation is Magic" # will set 'og:site_name'
description = "Lerning new things, while making (and breaking) stuff"  # will set 'og:description'

[params.gitalk]
  owner = "pechenkin655"
  repo = "pechenkin655.github.io"
  client_id = "d41a509c14d99d4478ac"
  client_secret = "d5c879d49a47243584c30e1beb7963e94b1c4d4b"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "Категории"
weight = 2
[[menu.main]]
url = "/tags"
name = "Теги"
weight = 3
[[menu.main]]
url = "/posts/"
name = "Архив"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4
